Puntos Clave

1. Una función es un bloque de código que realiza una tarea especifica cuando la función es llamada (invocada). Las funciones son útiles para hacer que el código sea reutilizable, que este mejor organizado y más legible. Las funciones contienen parámetros y pueden regresar valores.

2. Existen al menos cuatro tipos de funciones básicas en Python:

Funciones integradas las cuales son partes importantes de Python (como lo es la función print()). Puedes ver una lista completa de las funciones integradas de Python en la siguiente liga: https://docs.python.org/3/library/functions.html.
También están las que se encuentran en módulos pre-instalados (se hablará acerca de ellas en el curso Fundamentos de Python 2).
Funciones definidas por el usuario las cuales son escritas por los programadores para los programadores, puedes escribir tus propias funciones y utilizarlas libremente en tu código.
Las funciones lambda (aprenderás acerca de ellas en el curso Fundamentos de Python 2).
3. Las funciones propias se pueden definir utilizando la palabra reservada def y con la siguiente sintaxis:

def your_function(optional parameters):
    # el cuerpo de la función


Se puede definir una función sin que haga uso de argumentos, por ejemplo:

def message():    # definiendo una función
    print("Hello")    # cuerpo de la función

message()    # invocación de la función


También es posible definir funciones con argumentos, como la siguiente que contiene un solo parámetro:

def hello(name):    # definiendo una función
    print("Hola,", name)    # cuerpo de la función


name = input("Ingresa tu nombre: ")

hello(name)    # invocación de la función


Se hablará más sobre las funciones parametrizadas en la siguiente sección. No te preocupes.

Ejercicio 1

La función input() es un ejemplo de:

a) una función definida por el usuario
b) una función integrada

Revisar
b â es una función integrada


Ejercicio 2

¿Qué es lo que ocurre cuando se invoca una función antes de ser definida? Ejemplo:

hi()

def hi():
    print("¡Hola!")


Revisar
Se genera una excepción (la excepción NameError)


Ejercicio 3

¿Qué es lo que ocurrirá cuando se ejecute el siguiente código?

def hi():
    print("hola")

hi(5)


Revisar
Se genera una excepción (la excepción TypeError) â la función hi() no toma argumentos